name: "Build Test and Push Docker Images"

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab
  # schedule:
  #   - cron: '0 14 * * 1'  # Runs every Monday at 10:00 AM EDT

jobs:
  define_jobs:
    name: Define Jobs
    runs-on: ubuntu-latest
    outputs:
      jobs: ${{ steps.generate-jobs.outputs.jobs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate jobs
        id: generate-jobs
        run: |
          jobs=$(jq -c '
            to_entries[] |
            select(.key | test("^\\d+\\.\\d+$")) | # Exclude preview versions like `3.4-rc`
            select(.value != null) | # Exclude empty versions
            {
              minor_version: .key,
              patch_version: .value.version,
              variants: .value.variants
            } |
            .variants[] as $variant |
            {
              minor_version,
              patch_version,
              variant: $variant
            }
          ' versions.json | jq -s '.')
          echo "jobs=$(echo $jobs | jq -c)" >> "$GITHUB_OUTPUT"

  build_test_push:
    name: "Build Test and Push Ruby ${{ matrix.patch_version}} for ${{ matrix.variant }}"
    needs: define_jobs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.define_jobs.outputs.jobs) }}
    steps:
      - name: Print placeholder message for ${{ matrix.patch_version }}
        run: |
          echo "TODO: build test and push ${{ matrix.patch_version }} / ${{ matrix.minor_version }} / ${{ matrix.variant }}"
