name: "Build Test and Push Docker Images"

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab
  # schedule:
  #   - cron: '0 14 * * 1'  # Runs every Monday at 10:00 AM EDT

jobs:
  define_jobs:
    name: Define Jobs
    runs-on: ubuntu-latest
    outputs:
      jobs: ${{ steps.generate-jobs.outputs.jobs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate jobs
        id: generate-jobs
        run: |
          jobs=$(jq -c '
            to_entries[] |
            select(.value != null) |
            {
              minor_version: .key,
              full_version: .value.version,
              variants: .value.variants
            } |
            .variants[] as $variant |
            {
              minor_version,
              full_version,
              variant: $variant
            }
          ' versions.json)
          echo "jobs=$jobs" >> "$GITHUB_OUTPUT"

  build_test_push:
    name: Build Test and Push Images
    needs: define_jobs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: ${{ fromJson(needs.define_jobs.outputs.jobs) }}

    steps:
      - name: Print placeholder message for ${{ matrix.patch_version }}
        run: |
          echo "TODO: build test and push ${matrix.job.patch_version} / ${matrix.job.minor_version} / ${matrix.job.variant}"
